apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t1n7dh75c-go 
  janus-idp.io/tekton: t1n7dh75c-go
  backstage.io/kubernetes-id: t1n7dh75c-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t1n7dh75c-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml